// context of a declaration
export const DECLARATION_BROADCAST = 'DECLARATION_BROADCAST';
export const DECLARATION_SUB = 'DECLARATION_SUB';
export const DECLARATION_SUB_IMMEDIATE = 'DECLARATION_SUB_IMMEDIATE';
